kind: pipeline
name: default

steps:
  - name: build
    image: golang:alpine
    environment:
      CGO_ENABLED: 0
    commands:
      - apk add --no-cache git
      - go build -o ldaphttpauth .
      - tar zcf ldaphttpauth.tar.gz ldaphttpauth

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - ldaphttpauth.tar.gz
      checksum:
        - sha256
    when:
      event: tag
